# Generated by Django 5.1.4 on 2024-12-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='otp_email',
            field=models.EmailField(default='default@example,com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5e5a8c', max_length=6),
        ),
    ]
