# Generated by Django 5.1.4 on 2024-12-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_email',
            field=models.EmailField(max_length=254),
        ),
    ]
